#!/usr/bin/python
print("Content-type:text/html\r\n\r\n")
print('<html>')
print('<head>')
print('<title>Hello word-first CGI program</title>')
print('<head>')
print('<body>')
print('<h2>Hello word this is first CGI program</h2>')
print('</body>')
print('</html>')
